sudo: false
language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
bundler_args: --binstubs
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
script:
  - ./scripts/test
