sudo: false
language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
bundler_args: --binstubs
before_install:
  - sudo apt-get update && sudo apt-get install apt-transport-https ca-certificates -y && sudo update-ca-certificates
  - gem update --system
  - gem install bundler
dist: focal
script:
  - ./scripts/test
